
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWS", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWS {


    /**
     * 
     * @param password
     * @param roles
     * @param email
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterUser", targetNamespace = "http://Service/", className = "service.AjouterUser")
    @ResponseWrapper(localName = "ajouterUserResponse", targetNamespace = "http://Service/", className = "service.AjouterUserResponse")
    @Action(input = "http://Service/UserWS/ajouterUserRequest", output = "http://Service/UserWS/ajouterUserResponse")
    public Boolean ajouterUser(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "roles", targetNamespace = "")
        String roles);

    /**
     * 
     * @param password
     * @param roles
     * @param id
     * @param email
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifierUser", targetNamespace = "http://Service/", className = "service.ModifierUser")
    @ResponseWrapper(localName = "modifierUserResponse", targetNamespace = "http://Service/", className = "service.ModifierUserResponse")
    @Action(input = "http://Service/UserWS/modifierUserRequest", output = "http://Service/UserWS/modifierUserResponse")
    public Boolean modifierUser(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "roles", targetNamespace = "")
        String roles);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimerUser", targetNamespace = "http://Service/", className = "service.SupprimerUser")
    @ResponseWrapper(localName = "supprimerUserResponse", targetNamespace = "http://Service/", className = "service.SupprimerUserResponse")
    @Action(input = "http://Service/UserWS/supprimerUserRequest", output = "http://Service/UserWS/supprimerUserResponse")
    public Boolean supprimerUser(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param password
     * @param email
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connexionUser", targetNamespace = "http://Service/", className = "service.ConnexionUser")
    @ResponseWrapper(localName = "connexionUserResponse", targetNamespace = "http://Service/", className = "service.ConnexionUserResponse")
    @Action(input = "http://Service/UserWS/connexionUserRequest", output = "http://Service/UserWS/connexionUserResponse")
    public boolean connexionUser(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @return
     *     returns java.util.List<service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://Service/", className = "service.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://Service/", className = "service.GetUsersResponse")
    @Action(input = "http://Service/UserWS/getUsersRequest", output = "http://Service/UserWS/getUsersResponse")
    public List<User> getUsers();

}
